#!/usr/bin/env python3
"""Sync the cate-hq/platform GitHub repo into the Ridgewells project note.

Two jobs (pull-only, repo -> vault):
  1. Progress digest: append new commits / merged PRs / open issues to the
     project note's ## Log. Idempotent: items already present in the note
     (by short SHA or #PR) are skipped, so re-runs never double-log.
  2. Docs mirror: copy key root docs + all docs/**.md into a read-only,
     gitignored mirror folder so design context is readable in Obsidian.

Runs graceful: any gh/network failure prints a [skip] line and exits 0,
mirroring the gcalcli import pattern in /today.

Usage:
  python3 sync-ridgewells.py            # dry-run (report only)
  python3 sync-ridgewells.py --apply    # write digest + refresh mirror
"""
import base64
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = "cate-hq/platform"
VAULT = Path(__file__).resolve().parents[2]
PROJECT_DIR = VAULT / "00 Human/30 Projects/Ridgewells"
PROJECT_NOTE = PROJECT_DIR / "Ridgewells.md"
MIRROR = PROJECT_DIR / "repo-docs"
STATE = Path(__file__).resolve().parent / ".ridgewells-sync-state.json"

# Root files worth mirroring, plus everything under docs/ that is markdown.
ROOT_DOCS = ["README.md", "STRATEGY.md", "CONCEPTS.md", "AGENTS.md"]
FALLBACK_DAYS = 14  # lookback when no prior state exists


class GhError(Exception):
    pass


def gh(args, parse=True):
    """Run a gh command; return parsed JSON (or raw text). Raise on failure."""
    try:
        out = subprocess.run(
            ["gh", *args],
            capture_output=True, text=True, timeout=60,
        )
    except FileNotFoundError:
        raise GhError("gh CLI not installed")
    except subprocess.TimeoutExpired:
        raise GhError("gh timed out")
    if out.returncode != 0:
        raise GhError(out.stderr.strip() or f"gh exited {out.returncode}")
    return json.loads(out.stdout) if parse else out.stdout


def load_state():
    if STATE.exists():
        try:
            return json.loads(STATE.read_text())
        except json.JSONDecodeError:
            pass
    return {}


def since_iso(state):
    if state.get("last_run"):
        return state["last_run"]
    return (datetime.now(timezone.utc) - timedelta(days=FALLBACK_DAYS)).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )


def fetch_progress(since):
    """Return (commits, merged_prs, open_issues) since the given ISO timestamp."""
    commits = gh(["api", f"repos/{REPO}/commits?since={since}&per_page=100"])
    commits = [
        {
            "sha": c["sha"][:7],
            "msg": c["commit"]["message"].splitlines()[0].strip(),
        }
        for c in commits
    ]
    prs = gh([
        "pr", "list", "--repo", REPO, "--state", "merged",
        "--limit", "50", "--json", "number,title,mergedAt",
    ])
    prs = [p for p in prs if p.get("mergedAt", "") >= since]
    issues = gh([
        "issue", "list", "--repo", REPO, "--state", "open",
        "--limit", "50", "--json", "number,title",
    ])
    return commits, prs, issues


def already_logged(note_text):
    """Short SHAs and PR/issue numbers already present in the note."""
    shas = set(re.findall(r"\b[0-9a-f]{7}\b", note_text))
    nums = set(re.findall(r"#(\d+)", note_text))
    return shas, nums


def build_digest_block(commits, prs, issues, now):
    lines = [f"### {now:%Y-%m-%d} (repo sync {now:%H:%M})"]
    if commits:
        shown = "; ".join(f"`{c['sha']}` {c['msg']}" for c in commits[:15])
        extra = f" (+{len(commits) - 15} more)" if len(commits) > 15 else ""
        lines.append(f"- Commits ({len(commits)}): {shown}{extra}")
    if prs:
        shown = "; ".join(f"#{p['number']} {p['title']}" for p in prs[:10])
        lines.append(f"- Merged PRs ({len(prs)}): {shown}")
    if issues:
        shown = "; ".join(f"#{i['number']} {i['title']}" for i in issues[:10])
        lines.append(f"- Open issues ({len(issues)}): {shown}")
    lines.append(f"- Docs mirrored to `repo-docs/` from {REPO}.")
    return "\n".join(lines)


def list_doc_paths():
    """Root docs that exist + all markdown under docs/."""
    tree = gh(["api", f"repos/{REPO}/git/trees/HEAD?recursive=1"])["tree"]
    paths = [t["path"] for t in tree if t["type"] == "blob"]
    docs = [p for p in paths if p in ROOT_DOCS]
    docs += [p for p in paths if p.startswith("docs/") and p.endswith(".md")]
    return sorted(set(docs))


def fetch_file(path):
    blob = gh(["api", f"repos/{REPO}/contents/{path}"])
    return base64.b64decode(blob["content"]).decode("utf-8", "replace")


def refresh_mirror(paths, now):
    import shutil
    if MIRROR.exists():
        shutil.rmtree(MIRROR)
    MIRROR.mkdir(parents=True)
    (MIRROR / "_GENERATED.md").write_text(
        "---\ntags: [generated]\n---\n\n"
        f"# repo-docs (generated mirror)\n\n"
        f"> Read-only mirror of `{REPO}` docs. Do NOT edit here; changes belong "
        f"in the repo. Regenerated by `Machine/Scripts/sync-ridgewells.py`.\n"
        f"> Last synced: {now:%Y-%m-%d %H:%M}.\n",
        encoding="utf-8",
    )
    for path in paths:
        dest = MIRROR / path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(fetch_file(path), encoding="utf-8")


def main():
    apply = "--apply" in sys.argv
    now = datetime.now().astimezone()
    state = load_state()
    since = since_iso(state)

    try:
        commits, prs, issues = fetch_progress(since)
        doc_paths = list_doc_paths()
    except GhError as e:
        print(f"[skip] Ridgewells sync: {e}")
        return 0

    note_text = PROJECT_NOTE.read_text(encoding="utf-8")
    seen_shas, seen_nums = already_logged(note_text)
    new_commits = [c for c in commits if c["sha"] not in seen_shas]
    new_prs = [p for p in prs if str(p["number"]) not in seen_nums]

    have_progress = bool(new_commits or new_prs)
    print(
        f"{'APPLY' if apply else 'DRY-RUN'}: "
        f"{len(new_commits)} new commits, {len(new_prs)} new merged PRs, "
        f"{len(issues)} open issues, {len(doc_paths)} docs to mirror."
    )

    if not apply:
        if have_progress:
            print("\n--- digest preview ---")
            print(build_digest_block(new_commits, new_prs, issues, now))
        return 0

    # 1. Docs mirror (always refresh so the read is current)
    refresh_mirror(doc_paths, now)

    # 2. Progress digest (only if there is something new)
    if have_progress:
        block = build_digest_block(new_commits, new_prs, issues, now)
        note_text = note_text.rstrip() + "\n" + block + "\n"
        PROJECT_NOTE.write_text(note_text, encoding="utf-8")

    # 3. Persist state window (newest commit timestamp = next 'since')
    state["last_run"] = now.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    STATE.write_text(json.dumps(state, indent=2), encoding="utf-8")
    print("Done." if have_progress else "Done (mirror only; no new activity).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
